# Copyright (c) the JPEG XL Project Authors.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

# Workflow for building the release binaries.
#
# This workflow runs as a post-submit step, when pushing to main or the release
# branches (v*.*.x), and when creating a release in GitHub.
#
# In the GitHub release case, in addition to build the release binaries it also
# uploads the binaries to the given release automatically.

name: Release build / upload
on:
  merge_group:
  push:
    branches:
      - main
      - v*.*.x
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
    paths-ignore:
      - '**.md'
      - 'AUTHORS'
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ubuntu_static_x86_64:
    name: linux x86_64 static
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'CI:none') }}
    runs-on: [ubuntu-latest]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: Install build deps
      run: |
        sudo rm -f /var/lib/man-db/auto-update
        sudo apt update
        sudo apt install -y \
          asciidoc \
          clang \
          cmake \
          doxygen \
          graphviz \
          libgif-dev \
          libgtest-dev \
          libjpeg-dev \
          libopenexr-dev \
          libpng-dev \
          libwebp-dev \
          ninja-build \
          pkg-config \
          zip \
        #
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

    - name: Checkout the source
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: true
        fetch-depth: 1

    - name: Build
      run: |
        SKIP_TEST=1 \
        ./ci.sh release \
          -DJPEGLI_DEP_LICENSE_DIR=/usr/share/doc \
          -DJPEGLI_STATIC=ON \
          -DBUILD_TESTING=OFF \
          -DJPEGLI_ENABLE_JPEGLI_LIBJPEG=OFF \
          -DJPEGLI_ENABLE_OPENEXR=OFF \
          -DJPEGLI_ENABLE_DEVTOOLS=OFF \

    - name: Package release zip
      run: |
        cd build
        zip -j ${{ runner.workspace }}/jpegli-linux-x86_64-static.zip \
          LICENSE* tools/{cjpegli,djpegli}

    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: jpegli-linux-x86_64-static
        path: ${{ runner.workspace }}/jpegli-linux-x86_64-static.zip
        compression-level: 0


  windows_build:
    name: windows x64 static Release
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'CI:none') }}
    runs-on: [windows-2022]

    env:
      VCPKG_VERSION: '2025.10.17'
      VCPKG_ROOT: vcpkg
      VCPKG_DISABLE_METRICS: 1
      BUILD_TYPE: Release
      PREFIX: x64-windows-static

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: Checkout the source
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: true
        fetch-depth: 2

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      id: cache-vcpkg
      with:
        path: vcpkg
        key: release-${{ runner.os }}-vcpkg-${{ env.VCPKG_VERSION }}-x64-windows-static

    - name: Download vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      # wget doesn't seem to work under bash.
      shell: 'powershell'
      run: |
        C:\msys64\usr\bin\wget.exe -nv `
           https://github.com/microsoft/vcpkg/archive/refs/tags/${{ env.VCPKG_VERSION }}.zip `
          -O vcpkg.zip
    - name: Bootstrap vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      shell: 'bash'
      run: |
        set -x
        unzip -q vcpkg.zip
        rm -rf ${VCPKG_ROOT}
        mv vcpkg-${VCPKG_VERSION} ${VCPKG_ROOT}
        ${VCPKG_ROOT}/bootstrap-vcpkg.sh

    - name: Install libraries with vcpkg
      shell: 'bash'
      run: |
        set -x
        ${VCPKG_ROOT}/vcpkg --triplet x64-windows-static install \
          giflib \
          libjpeg-turbo \
          libpng \
          libwebp \
          pkgconf \
        #

    - name: Configure
      shell: 'bash'
      run: |
        set -x
        mkdir build
        cmake -Bbuild -H. -A x64 \
          -DJPEGLI_STATIC=ON \
          -DJPEGLI_ENABLE_TOOLS=ON \
          -DBUILD_TESTING=OFF \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DCMAKE_INSTALL_PREFIX=`pwd`/${PREFIX} \
          -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake \
          -DJPEGLI_ENABLE_JPEGLI_LIBJPEG=OFF \
          -DJPEGLI_ENABLE_OPENEXR=OFF \
          -DJPEGLI_ENABLE_TCMALLOC=OFF \
          -DJPEGLI_ENABLE_DEVTOOLS=OFF \
          -DVCPKG_TARGET_TRIPLET=x64-windows-static \
        #
    - name: Build
      shell: 'bash'
      run: |
        set -x
        cmake --build build --config ${{ env.BUILD_TYPE }}
    - name: Install
      shell: 'bash'
      run: |
        set -x
        cmake --build build --config ${{ env.BUILD_TYPE }} --target install
        for pkg in giflib libjpeg-turbo libpng libwebp zlib; do
          cp vcpkg/installed/x64-windows-static/share/${pkg}/copyright \
            ${PREFIX}/bin/LICENSE.${pkg}
        done
        cp third_party/sjpeg/COPYING ${PREFIX}/bin/LICENSE.sjpeg
        cp third_party/skcms/LICENSE ${PREFIX}/bin/LICENSE.skcms
        cp third_party/highway/LICENSE ${PREFIX}/bin/LICENSE.highway
        cp LICENSE ${PREFIX}/bin/LICENSE.jpegli

    - name: Package release
      shell: 'bash'
      run: |
        7z -tzip a jpegli-windows-x64-static.zip ${PREFIX}/bin/* ${PREFIX}/lib/*

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: jpegli-windows-x64-static
        path: jpegli-windows-x64-static.zip
        compression-level: 0


  publish_release_assets:
    name: Publish release assets
    needs: [ubuntu_static_x86_64, windows_build]
    if: github.event_name == 'release'
    runs-on: [ubuntu-latest]
    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        path: release_assets
        merge-multiple: true

    - name: Publish assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
      run: |
        gh release upload "${{ github.event.release.tag_name }}" ./release_assets/*.zip --clobber
